#pragma once

#include "../ZeroEngineStd.h"

namespace ZeroEngine {

   enum AppMsgType {
        MSG_BEGIN,
        NULL_MSG,
        QUIT_MSG,
        UNHANDLED_MSG,
        WINDOW_MSG,
        SYSTEM_MSG,
        KEYDOWN_MSG,
        KEYUP_MSG,
        KEYBOARD_MSG,
        TEXT_EDIT_MSG,
        TEXT_INPUT_MSG,
        KEYMAP_CHANGE_MSG,
        MOUSE_MOTION_MSG,
        MOUSE_BUTTON_DOWN_MSG,
        MOUSE_BUTTON_UP_MSG,
        MOUSE_WHEEL_MSG,
        JOY_AXIS_MOTION_MSG,
        JOY_BALL_MOTION_MSG,
        JOY_HAT_MOTION_MSG,
        JOY_BUTTON_DOWN_MSG,
        JOY_BUTTON_UP_MSG,
        JOY_DEVICE_ADDED_MSG,
        JOY_DEVICE_REMOVED_MSG,
        CONTROLLER_AXIS_MOTION_MSG,
        CONTROLLER_BUTTON_DOWN_MSG,
        CONTROLLER_BUTTON_UP_MSG,
        CONTROLLER_DEVICE_ADDED_MSG,
        CONTROLLER_DEVICE_REMOVED_MSG,
        CONTROLLER_DEVICE_REMAPPED_MSG,
        FINGER_DOWN_MSG,
        FINGER_UP_MSG,
        FINGER_MOTION_MSG,
        CLIPBOARD_MSG,
        DROP_FILE_MSG,
        DROP_TEXT_MSG,
        DROP_BEGIN_MSG,
        DROP_COMPLETE_MSG,
        AUDIO_DEVICE_ADDED_MSG,
        AUDIO_DEVICE_REMOVED_MSG,
        RENDER_TARGETS_RESET_MSG,
        RENDER_DEVICE_RESET_MSG,
        MSG_END
    };
}