
// @TODO: CLean this up so that each directory has a core include file

#include "ZeroEngineStd.h"
#include "Framework/Framework.h"
#include "Utils/MemoryPool.h"
#include "Logger/Logger.h"
#include "Graphics/Graphics.h"
#include "AppLayer/AppLayer.h"
#include "Input/Input.h"
#include "Events/Events.h"
#include "Events/EventListener.h"
#include "Entity\Entity.h"
#include "Entity\EntityFactory.h"
#include "ZeroEngineEvents.h"
#include "ZeroEngineProcesses.h"
#include "GameLogic\GameLogicInclude.h"
#include "GameView\GameViewInclude.h"
#include "GameView/Sprite.h"
#include "Framework/ITexture.h"
#include "ZeroEngineScreenElements.h"
#include "AppLayer/Game.h"
#include "Rendering/IRenderPacket.h"
#include "Rendering/RenderPacketTypes.h"
#include "Launcher/GameLauncher.h"
#include "Math/Math.h"
#include "Math/Vector2.h"
#include "Math/Vector3.h"
#include "Math/Vector4.h"
#include "Utils/Xml/XmlReader.h"
#include "Utils/Xml/XmlWriter.h"
#include "Entity/Components/ScreenElementRenderComponent.h"
#include "Entity/Components/SpriteRenderComponent.h"
#include "Entity/Components/TransformComponent2D.h"
